global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: /actuator/prometheus
    scrape_interval: 1m
    static_configs:
      - targets:
        - 192.168.0.12:8080 # use this local machine IP accessbile from docker container (cmd: ifconfig)
